src/clusterserve/config/routes.rb
Clusterserve::Application.routes.draw do
  resources :feature_values
  resources :classifications
  resources :runs do
    resources :clusters, shallow: true
  end

  resources :experiments

  root to: 'runs#index'

end

src/clusterserve/app/models/classification.rb
class Classification < ActiveRecord::Base
  belongs_to :cluster
  has_many :feature_values

  def data
    Hash[feature_values.map {|fv| [fv.feature, fv.value] }].symbolize_keys
  end
end

src/clusterserve/app/models/cluster.rb
class Cluster < ActiveRecord::Base
  belongs_to :run
  has_many :classifications
  has_many :feature_values, through: :classifications
  has_many :cluster_statistics, :class_name => "ClusterStatistics"

  def self.n_largest(n)
    ids = select('clusters.id, count(classifications.id) AS classification_count').
          joins(:classifications).
          group('clusters.id').
          order('classification_count DESC').
          limit(n).map {|obj| obj.id }

    where(id: ids)
  end

  # The features and the center values are assumed to be in the same order
  serialize :center

  def center
    super.map {|n| n.round(3) }
  end

  def features
    run.features
  end

  def pretty_center
    Hash[features.zip(center)]
  end

  def size
    classifications.count
  end

  def statistics
    stats = features.map {|f| feature_statistics(f) }

    Hash[features.zip(stats)]
  end

  def feature_statistics(feature)
    begin
      stats = cluster_statistics.find_by!(feature: feature)
    rescue ActiveRecord::RecordNotFound
      values = values_for_feature(feature)
      normalized_values = normalized_values_for_feature(feature)

      mean = values.sum.to_f / values.length
      normalized_mean = normalized_values.sum.to_f / normalized_values.length

      stats = cluster_statistics.create(feature: feature, mean: mean, normalized_mean: normalized_mean)
      # StatisticsWorker.perform_async(stats.id)
    end

    stats
  end

  def values_for_feature(feature)
    fieldset_for_feature(feature, :value)
  end

  def normalized_values_for_feature(feature)
    fieldset_for_feature(feature, :normalized_value)
  end

  protected

  def fieldset_for_feature(feature, field)
    FeatureValue.where(feature: feature, classification_id: classifications.map(&:id)).map(&field)
  end

  def serializable_hash(options={})
    super(options.merge(methods: [:size]))
  end
end

src/clusterserve/app/models/cluster_statistics.rb
class ClusterStatistics < ActiveRecord::Base
  belongs_to :cluster

  after_initialize :override_defaults

  def override_defaults
    ClusterStatistics.statistics_fields.each do |field|
      class_eval do
        define_method(field) { self[field].present? ? self[field] : 0.0 }
      end
    end
  end

  def to_hash
    Hash[self.class.statistics_fields.zip(statistics_values)]
  end

  protected

  def statistics_values
    self.class.statistics_fields.map {|field| send(field) }
  end

  def self.statistics_fields
    [:number, :sum, :variance, :standard_deviation, :min, :max, :mean, :mode, :median, :range, :q1, :q2, :q3]
  end
end

src/clusterserve/app/models/feature_value.rb
class FeatureValue < ActiveRecord::Base
  belongs_to :classification

  def feature
    self[:feature].to_sym
  end
end

src/clusterserve/app/models/run.rb
class Run < ActiveRecord::Base
  has_many :clusters
  has_many :classifications, through: :clusters
  has_many :feature_values, through: :classifications

  default_scope -> { order('created_at DESC') }

  serialize :features

  def params
    JSON.parse(self[:params]).symbolize_keys
  end

  def features
    self[:features].map(&:to_sym)
  end

  def size
    clusters.collect(&:size).sum
  end

  def feature_average(feature)
    feature_index = features.index(feature)
    clusters.collect {|c| c.center[feature_index] * c.size }.sum.to_f / self.size
  end

  def feature_averages
    Hash[features.zip(features.map {|f| feature_average(f) })]
  end

  def timespan_from
    self[:timespan_from] ? Time.at(self[:timespan_from]).to_datetime : nil
  end
  def timespan_to
    self[:timespan_from] ? Time.at(self[:timespan_to]).to_datetime : nil
  end
end

src/clusterserve/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

src/clusterserve/app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
end

src/clusterserve/app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  respond_to :json

  def index
    @run = Run.find(params[:run_id])
    @clusters = @run.clusters

    respond_with @clusters
  end
end

src/clusterserve/app/controllers/feature_values_controller.rb
class FeatureValuesController < ApplicationController
end

src/clusterserve/app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
    @clusters = @run.clusters.n_largest(params[:n] || @run.clusters.count).sort_by(&:size).reverse
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render action: 'show', status: :created, location: @run }
      else
        format.html { render action: 'new' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def run_params
      params.require(:run).permit(:algorithm, :params, :comment)
    end
end

src/clusterserve/app/helpers/application_helper.rb
module ApplicationHelper
end

src/clusterserve/app/helpers/classifications_helper.rb
module ClassificationsHelper
end

src/clusterserve/app/helpers/clusters_helper.rb
module ClustersHelper
end

src/clusterserve/app/helpers/feature_values_helper.rb
module FeatureValuesHelper
end

src/clusterserve/app/helpers/runs_helper.rb
module RunsHelper
end

src/clusterserve/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    = viewport_meta_tag
    %title= content_for?(:title) ? yield(:title) : "Clusterserve"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'


  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button(type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse")
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand(href=root_path) Clusterserve
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Analyze clusters", runs_path
            / %li= link_to "Experiments", experiments_path

    .container
      .row
        .col-md-12
          = bootstrap_flash
          = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

src/clusterserve/app/views/layouts/application2.html.haml
!!! 5
%html
  %head
    %title Clusterserve
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

src/clusterserve/app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :algorithm %><br>
    <%= f.text_field :algorithm %>
  </div>
  <div class="field">
    <%= f.label :params %><br>
    <%= f.text_field :params %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/clusterserve/app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

src/clusterserve/app/views/runs/index.html.haml
%h1 Runs

%table.table
  %thead
    %tr
      %th Run
      %th Algorithm
      %th Cluster count
      %th Features
      %th Davies bouldin index
      %th Avg. cluster size
      %th Median cluster size
      %th Month
  %tbody
    - @runs.each do |run|
      %tr
        %td= link_to l(run.created_at, format: :long), run
        %td= run.algorithm
        %td= run.clusters.count
        %td{ title: run.features.join(", ") }= run.features.count
        %td= run.eval_db
        %td= run.clusters.collect(&:size).sum / run.clusters.count
        %td= run.clusters.collect(&:size)[run.clusters.count / 2]
        %td= run.timespan_from ? l(run.timespan_from, format: '%B') : "-"

src/clusterserve/app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

src/clusterserve/app/views/runs/show.html.haml
%p#notice= notice

%h1 #{@run.algorithm} (#{@run.clusters.count} clusters)

.row
  .col-md-8
    .panel.panel-default
      .panel-heading
        %h2.panel-title Cluster comparison
      %section#comparison.panel-body{ title: "Cluster comparison", data: { clusters: @clusters.to_json, features: @run.features.to_json } }
        %div.container{ style: 'width: 500px; height: 350px;' }
      %form.panel-footer.form{ action: '', method: 'get' }
        %p
          %label{ for: 'n' }
            Number of clusters to visualize (sorted by number of members)
          %br
          %input.pull-left{ id: 'n', type: 'range', name: 'n', min: 1, max: @run.clusters.count, value: params[:n] || @run.clusters.count, oninput: '_n.value = n.value' }
          %output{ for: 'n', name: '_n' }= params[:n] || @run.clusters.count
        = submit_tag 'Update', name: nil

    - @clusters.each do |cluster|
      .panel.panel-default
        .panel-heading
          %h2.panel-title
            = cluster.label || "Cluster #{@clusters.index(cluster) + 1}"
            %small id: #{cluster.id}
            %p.pull-right
              #{cluster.size} samples
        %table.table.table-bordered
          %tr
            %td.col-md-8{ rowspan: cluster.statistics.length }
              %figure.cluster.small-visualization{ data: { center: cluster.center.to_json, avg_center: @run.feature_averages.values.to_json, features: 1.upto(@run.features.length).map(&:to_s).to_json } }
                %canvas.container{ width: 390, height: 300 }
            %th 1. #{cluster.features.first}
            %td.numeric= sprintf("%.2f", cluster.feature_statistics(cluster.features.first).mean.round(2))
          - for feature in cluster.features.from(1)
            %tr
              %th #{cluster.features.index(feature) + 1}.&nbsp;#{feature}
              %td.numeric= sprintf("%.2f", cluster.feature_statistics(feature).mean.round(2))

  .col-md-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title Meta
      %dl.panel-body
        - if @run.timespan_from && @run.timespan_to
          %dt Data for month
          %dd
            %p= l(@run.timespan_from, format: '%B %Y')
        %dt Evaluation (davies-bouldin index)
        %dd
          %p= @run.eval_db
        %dt Features
        %dd
          %ol
            - for feature in @run.features
              %li= feature
        %dt Run params
        %dd
          %ul
            - @run.params.each do |key, value|
              %li
                %strong= key.to_s + ":"
                = value
        %dt Comment
        %dd= @run.comment || '-'


/ %ol
/   - @run.clusters.each do |cluster|
/     = render 'visual/cluster_small', cluster: cluster

%p
  = link_to "« Back to latest runs", runs_path

src/clusterserve/app/views/visual/_cluster_small.html.haml
%li.cluster.small-visualization{ title: cluster.label, data: { center: cluster.center.to_json, features: cluster.features.to_json } }
  %div{ style: 'width: 500px; height: 400px;' }